export { default as About } from './About'
export { default as Home } from './Home'
export { default as VanDetail } from './Vans/VanDetail'
export { default as Vans } from './Vans/Vans'

export { default as Dashboard } from './Host/Dashboard'
export { default as Income } from './Host/Income'
export { default as Reviews } from './Host/Reviews'
export { default as HostVans} from './Host/HostVans'
export {default as HostVanDetail} from './Host/HostVanDetail'
export { default as HostVanInfo } from './Host/HostVanInfo'
export { default as HostVanPhoto } from './Host/HostVanPhoto'
export { default as HostVanPricing } from './Host/HostVanPricing'
export {default as ErrorPage } from './ErrorPage'